# This is a basic workflow to help you get started with Actions

name: test

on:
  push:
    tags:
      - "*"
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0 
          submodules: 'recursive'
      - uses: actions/setup-java@v3.5.0
        with:
          distribution: "temurin"
          java-version: "18"
      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.5.0
        with:
          babashka-version: 0.8.156
      - uses: DeLaGuardo/setup-clojure@9.5
        with:
          cli: 1.11.1.1155
      - run: make build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/ftr.jar, target/zen.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
