name: test

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0 
          submodules: 'recursive'
      - uses: actions/setup-java@v3.5.0
        with:
          distribution: "zulu"
          java-version: "8"
      - uses: DeLaGuardo/setup-clojure@9.5
        with:
          cli: 1.11.1.1155
      - run: make test
